version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: "products_postgres"
    environment:
      - 'POSTGRES_DB=products'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0000'
    ports:
      - "5433:5432"